# Generated by Django 5.1.2 on 2024-11-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_teacherprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='average_years_of_experience',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='number_of_classrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='number_of_subjects_offered',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='number_of_teachers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='percentage_of_qualified_teachers',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='teacher_to_student_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='total_enrollment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
