# Generated by Django 5.1.2 on 2024-11-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_school_average_years_of_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='established_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='total_facilities',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
