# Generated by Django 5.1.2 on 2024-12-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_guardianprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='subjects_taught',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='favorite_subjects',
            field=models.CharField(blank=True, help_text='Comma-separated list of favorite subjects.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, help_text='Subjects the teacher is proficient in.', related_name='teachers', to='account.subject'),
        ),
    ]
