# Generated by Django 5.1.2 on 2024-12-14 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_subject_remove_teacherprofile_subjects_taught_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Contact number for the school.', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='email_address',
            field=models.EmailField(blank=True, help_text='Official email address of the school.', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='facilities_summary',
            field=models.TextField(blank=True, help_text='Summary of key facilities (e.g., library, labs, sports fields).'),
        ),
        migrations.AddField(
            model_name='school',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='school_qrcodes/'),
        ),
        migrations.AddField(
            model_name='school',
            name='school_admin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_school', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='school',
            name='school_motto',
            field=models.CharField(blank=True, help_text='The motto or mission statement of the school.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='website',
            field=models.URLField(blank=True, help_text="School's official website.", null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='additional_languages',
            field=models.CharField(blank=True, help_text='Languages spoken other than English.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='awards_and_recognitions',
            field=models.TextField(blank=True, help_text='Details of awards or recognitions received.', null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Teacher’s contact number.', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='specialization',
            field=models.CharField(blank=True, choices=[('STEM', 'Science/STEM'), ('Arts', 'Arts'), ('Business', 'Business/Commercial')], help_text="Teacher's specialization area.", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='teaching_philosophy',
            field=models.TextField(blank=True, help_text="Brief description of the teacher's philosophy or approach.", null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='community_engagement',
            field=models.TextField(blank=True, help_text='Details about community involvement and initiatives.'),
        ),
        migrations.AlterField(
            model_name='school',
            name='extra_curricular_activities',
            field=models.TextField(blank=True, help_text='Details of extracurricular activities offered by the school.'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='performance_metrics',
            field=models.JSONField(blank=True, default=dict, help_text='Key performance indicators (e.g., exam pass rates).'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='certifications',
            field=models.CharField(blank=True, choices=[('GR', 'Graduate Teacher'), ('HTC', 'Higher Teacher’s Certificate'), ('PTC', 'Primary Teacher’s Certificate'), ('STC', 'Secondary Teacher’s Certificate')], help_text='Highest certification obtained.', max_length=20, null=True),
        ),
    ]
