# Generated by Django 5.1.2 on 2024-12-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_school_contact_number_school_email_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='ownership_type',
            field=models.CharField(blank=True, choices=[('Private', 'Private'), ('Government', 'Government')], max_length=20, null=True),
        ),
    ]
