# Generated by Django 5.1.2 on 2024-12-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_school_ownership_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='established_year',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='number_of_classrooms',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='ownership_type',
            field=models.CharField(blank=True, choices=[('Private', 'Private'), ('Government', 'Government')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='performance_metrics',
            field=models.JSONField(blank=True, db_index=True, default=dict, help_text='Key performance indicators (e.g., exam pass rates).'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Vocational', 'Vocational')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='school',
            name='teacher_to_student_ratio',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='total_enrollment',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
