# Generated by Django 5.1.2 on 2024-12-17 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_school_established_year_alter_school_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the district.', null=True)),
                ('region', models.CharField(choices=[('Eastern', 'Eastern'), ('Northern', 'Northern'), ('Southern', 'Southern'), ('Western', 'Western')], db_index=True, max_length=20)),
                ('population', models.IntegerField(blank=True, help_text='Population of the district.', null=True)),
                ('literacy_rate', models.FloatField(blank=True, help_text='Literacy rate in percentage.', null=True)),
                ('land_area_km2', models.FloatField(blank=True, help_text='Total land area in square kilometers.', null=True)),
                ('contact_number', models.CharField(blank=True, help_text='District office contact number.', max_length=15, null=True)),
                ('official_email', models.EmailField(blank=True, help_text='Official email of the district office.', max_length=254, null=True)),
                ('website', models.URLField(blank=True, help_text='Official district website.', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='is_governmental_approved',
            field=models.BooleanField(default=False, help_text='Is the school approved by the government?'),
        ),
        migrations.AddField(
            model_name='school',
            name='school_certificates',
            field=models.TextField(blank=True, help_text='Certificates offered (e.g., WASSCE, BECE, NPSE).', null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='take_bece',
            field=models.BooleanField(default=False, help_text='Does the school participate in BECE exams?'),
        ),
        migrations.AddField(
            model_name='school',
            name='take_npse',
            field=models.BooleanField(default=False, help_text='Does the school participate in NPSE exams?'),
        ),
        migrations.AddField(
            model_name='school',
            name='take_wassce',
            field=models.BooleanField(default=False, help_text='Does the school participate in WASSCE exams?'),
        ),
        migrations.AddField(
            model_name='school',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='account.district'),
        ),
    ]
