# Generated by Django 5.1.2 on 2024-12-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_district_school_is_governmental_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='subjects',
            field=models.ManyToManyField(blank=True, help_text='Subjects the teacher is proficient in.', related_name='subjects', to='account.subject'),
        ),
    ]
