# Generated by Django 5.1.2 on 2024-12-30 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_school_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='preferred_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('C', 'Completed'), ('X', 'Cancelled')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_requests', to='account.subject'),
        ),
        migrations.RemoveField(
            model_name='tutorprofile',
            name='subjects_expert_in',
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='subjects_expert_in',
            field=models.ManyToManyField(blank=True, related_name='tutors', to='account.subject'),
        ),
    ]
