# Generated by Django 5.1.2 on 2024-12-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_tutorprofile_rating_tutorrequest_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='certifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='degree_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='highest_education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='institution_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
