# Generated by Django 5.1.2 on 2024-12-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_tutorprofile_certifications_tutorprofile_degree_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='specialization',
            field=models.CharField(blank=True, choices=[('STEM', 'Science/STEM'), ('Arts', 'Arts'), ('Business', 'Business/Commercial')], help_text="Teacher's specialization area.", max_length=20, null=True),
        ),
    ]
