# Generated by Django 5.1.2 on 2024-11-06 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lessonplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SummarizedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_content', models.TextField()),
                ('summarized_content', models.TextField()),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('pdf', 'PDF'), ('csv', 'CSV')], max_length=50)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='summarized_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summarized_content', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
