# Generated by Django 5.1.2 on 2024-11-06 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_summarizedcontent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summarizedcontent',
            options={},
        ),
        migrations.RemoveField(
            model_name='summarizedcontent',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='summarizedcontent',
            name='uploaded_file',
        ),
        migrations.AddField(
            model_name='summarizedcontent',
            name='content_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarizedcontent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
