# Generated by Django 5.1.2 on 2024-11-06 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_summarizedcontent_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeWritingPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(blank=True, choices=[('adventure', 'Adventure'), ('mystery', 'Mystery'), ('historical', 'Historical Fiction'), ('fantasy', 'Fantasy'), ('realism', 'Realism'), ('comedy', 'Comedy')], max_length=50, null=True)),
                ('tone', models.CharField(blank=True, choices=[('inspirational', 'Inspirational'), ('playful', 'Playful'), ('serious', 'Serious'), ('sad', 'Sad'), ('hopeful', 'Hopeful')], max_length=50, null=True)),
                ('level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=50, null=True)),
                ('location', models.CharField(blank=True, choices=[('freetown', 'Freetown'), ('kenema', 'Kenema'), ('bo', 'Bo'), ('makeni', 'Makeni'), ('portloko', 'Port Loko'), ('kailahun', 'Kailahun'), ('other', 'Other')], default='freetown', max_length=50, null=True)),
                ('prompt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
