# Generated by Django 5.1.2 on 2024-11-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_creativewritingprompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativewritingprompt',
            name='idea',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creativewritingprompt',
            name='plot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creativewritingprompt',
            name='theme',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='creativewritingprompt',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
