# Generated by Django 5.1.2 on 2024-11-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_creativewritingprompt_idea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='follow_up_count',
            field=models.IntegerField(default=0),
        ),
    ]
