# Generated by Django 5.1.2 on 2024-12-19 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_district_school_is_governmental_approved_and_more'),
        ('core', '0007_lessonplan_follow_up_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_type', models.CharField(choices=[('library', 'Library'), ('science_lab', 'Science Lab'), ('computer_lab', 'Computer Lab'), ('sports_complex', 'Sports Complex'), ('auditorium', 'Auditorium'), ('cafeteria', 'Cafeteria'), ('clinic', 'Clinic'), ('playground', 'Playground'), ('art_room', 'Art Room'), ('music_room', 'Music Room'), ('other', 'Other')], default='other', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Font Awesome icon class (e.g., fas fa-book-reader)', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='facility_images/')),
                ('link', models.URLField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='account.school')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('youtube', 'YouTube Video'), ('document', 'Document'), ('other', 'Other')], default='image', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/')),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='account.school')),
            ],
        ),
    ]
