# Generated by Django 5.1.2 on 2024-12-20 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_school_subjects'),
        ('core', '0008_facility_media'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('guardian_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_relationship', models.CharField(blank=True, help_text='Relationship to the student', max_length=50, null=True)),
                ('guardian_contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_number', models.CharField(blank=True, help_text='Contact number of the applicant or guardian.', max_length=15, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('country', models.CharField(default='Sierra Leone', max_length=100)),
                ('passport_picture', models.ImageField(blank=True, null=True, upload_to='passport_pictures/')),
                ('application_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Distance Learning', 'Distance Learning')], db_index=True, default='Full-time', max_length=20)),
                ('school_level', models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Vocational', 'Vocational')], help_text='Level of schooling the applicant is applying for.', max_length=20)),
                ('class_level', models.CharField(choices=[('Class 1', 'Class 1'), ('Class 2', 'Class 2'), ('Class 3', 'Class 3'), ('Class 4', 'Class 4'), ('Class 5', 'Class 5'), ('Class 6', 'Class 6'), ('JSS 1', 'JSS 1'), ('JSS 2', 'JSS 2'), ('JSS 3', 'JSS 3'), ('SS 1', 'SS 1'), ('SS 2', 'SS 2'), ('SS 3', 'SS 3')], help_text='Class level the applicant is applying for.', max_length=20)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('application_code', models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn'), ('Interview_Scheduled', 'Interview Scheduled'), ('Interview_Completed', 'Interview Completed'), ('Waitlisted', 'Waitlisted')], db_index=True, default='Pending', max_length=20)),
                ('interview_date', models.DateField(blank=True, help_text='Date for the interview, if applicable.', null=True)),
                ('interview_feedback', models.TextField(blank=True, help_text='Feedback from the interview, if applicable.', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or remarks about the application.', null=True)),
                ('application_fee_paid', models.BooleanField(default=False, help_text='Has the application fee been paid?')),
                ('entrance_exam_score', models.FloatField(blank=True, help_text='Score of the entrance exam, if applicable.', null=True)),
                ('id_card', models.FileField(blank=True, help_text='Upload your ID card (PDF, PNG only).', null=True, upload_to='documents/id_cards/')),
                ('npse_result', models.FileField(blank=True, help_text='Upload your NPSE result (PDF, PNG only).', null=True, upload_to='documents/npse_results/')),
                ('bece_result', models.FileField(blank=True, help_text='Upload your BECE result (PDF, PNG only).', null=True, upload_to='documents/bece_results/')),
                ('birth_certificate', models.FileField(blank=True, help_text='Upload your birth certificate (PDF, PNG only).', null=True, upload_to='documents/birth_certificates/')),
                ('recommendation_letter_1', models.FileField(blank=True, help_text='Upload recommendation letter 1 (PDF, PNG only).', null=True, upload_to='documents/recommendation_letters/')),
                ('recommendation_letter_2', models.FileField(blank=True, help_text='Upload recommendation letter 2 (PDF, PNG only).', null=True, upload_to='documents/recommendation_letters/')),
                ('additional_documents', models.JSONField(blank=True, help_text='Links to any extra documents submitted with the application.', null=True)),
                ('admin_comments', models.TextField(blank=True, help_text='Internal comments from school admins regarding this application.', null=True)),
                ('last_status_change', models.DateTimeField(auto_now=True)),
                ('decision_date', models.DateField(blank=True, help_text='Date when the decision was made.', null=True)),
                ('application_deadline', models.DateField(blank=True, help_text='Deadline for submitting applications.', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('decision_made_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_decisions', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='account.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
            },
        ),
    ]
