# Generated by Django 5.1.2 on 2024-12-21 17:22

import core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_school_subjects'),
        ('core', '0009_application'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='additional_documents',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='admin_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='bece_result',
            field=models.FileField(blank=True, null=True, upload_to='documents/bece_results/', validators=[core.models.validate_file_type]),
        ),
        migrations.AlterField(
            model_name='application',
            name='birth_certificate',
            field=models.FileField(blank=True, null=True, upload_to='documents/birth_certificates/', validators=[core.models.validate_file_type]),
        ),
        migrations.AlterField(
            model_name='application',
            name='decision_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='entrance_exam_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='id_card',
            field=models.FileField(blank=True, null=True, upload_to='documents/id_cards/', validators=[core.models.validate_file_type]),
        ),
        migrations.AlterField(
            model_name='application',
            name='interview_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='interview_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='npse_result',
            field=models.FileField(blank=True, null=True, upload_to='documents/npse_results/', validators=[core.models.validate_file_type]),
        ),
        migrations.AlterField(
            model_name='application',
            name='recommendation_letter_1',
            field=models.FileField(blank=True, null=True, upload_to='documents/recommendation_letters/', validators=[core.models.validate_file_type]),
        ),
        migrations.AlterField(
            model_name='application',
            name='recommendation_letter_2',
            field=models.FileField(blank=True, null=True, upload_to='documents/recommendation_letters/', validators=[core.models.validate_file_type]),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='core_applic_status_148db8_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['application_date'], name='core_applic_applica_89fdb8_idx'),
        ),
    ]
