# Generated by Django 5.1.2 on 2024-12-26 12:57

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_application_previous_class_result_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='additional_documents',
        ),
        migrations.RemoveField(
            model_name='application',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='application',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='application',
            name='admin_comments',
        ),
        migrations.RemoveField(
            model_name='application',
            name='application_deadline',
        ),
        migrations.RemoveField(
            model_name='application',
            name='application_fee_paid',
        ),
        migrations.RemoveField(
            model_name='application',
            name='bece_result',
        ),
        migrations.RemoveField(
            model_name='application',
            name='birth_certificate',
        ),
        migrations.RemoveField(
            model_name='application',
            name='city',
        ),
        migrations.RemoveField(
            model_name='application',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='application',
            name='country',
        ),
        migrations.RemoveField(
            model_name='application',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='application',
            name='decision_date',
        ),
        migrations.RemoveField(
            model_name='application',
            name='decision_made_by',
        ),
        migrations.RemoveField(
            model_name='application',
            name='district',
        ),
        migrations.RemoveField(
            model_name='application',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='application',
            name='entrance_exam_score',
        ),
        migrations.RemoveField(
            model_name='application',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='application',
            name='guardian_contact_number',
        ),
        migrations.RemoveField(
            model_name='application',
            name='guardian_first_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='guardian_last_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='guardian_relationship',
        ),
        migrations.RemoveField(
            model_name='application',
            name='id_card',
        ),
        migrations.RemoveField(
            model_name='application',
            name='interview_feedback',
        ),
        migrations.RemoveField(
            model_name='application',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='last_status_change',
        ),
        migrations.RemoveField(
            model_name='application',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='application',
            name='npse_result',
        ),
        migrations.RemoveField(
            model_name='application',
            name='passport_picture',
        ),
        migrations.RemoveField(
            model_name='application',
            name='previous_class_result',
        ),
        migrations.RemoveField(
            model_name='application',
            name='recommendation_letter_1',
        ),
        migrations.RemoveField(
            model_name='application',
            name='recommendation_letter_2',
        ),
        migrations.RemoveField(
            model_name='application',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='application',
            name='student',
        ),
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('country', models.CharField(default='Sierra Leone', max_length=100)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='contact_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.contactinformation'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('passport_picture', 'Passport Picture'), ('id_card', 'ID Card'), ('npse_result', 'NPSE Result'), ('bece_result', 'BECE Result'), ('previous_class_result', 'Previous Class Result')], max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/', validators=[core.models.validate_file_type])),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.application')),
            ],
        ),
        migrations.CreateModel(
            name='GuardianInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_relationship', models.CharField(blank=True, help_text='Relationship to the student', max_length=50, null=True)),
                ('guardian_contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='guardian_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.guardianinformation'),
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='personal_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.personalinformation'),
        ),
    ]
