# Generated by Django 5.1.2 on 2024-12-28 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_application_additional_documents_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='application',
            name='core_applic_status_148db8_idx',
        ),
        migrations.RemoveIndex(
            model_name='application',
            name='core_applic_applica_89fdb8_idx',
        ),
        migrations.RemoveField(
            model_name='application',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='application',
            name='guardian_info',
        ),
        migrations.RemoveField(
            model_name='application',
            name='personal_info',
        ),
        migrations.RemoveField(
            model_name='application',
            name='previous_school_address',
        ),
        migrations.RemoveField(
            model_name='application',
            name='previous_school_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='school',
        ),
        migrations.RemoveField(
            model_name='contactinformation',
            name='student',
        ),
        migrations.RemoveField(
            model_name='guardianinformation',
            name='student',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='student',
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='core.application'),
        ),
        migrations.AddField(
            model_name='guardianinformation',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guardian_info', to='core.application'),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_info', to='core.application'),
        ),
        migrations.AlterField(
            model_name='application',
            name='class_level',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='school_level',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], db_index=True, default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.application'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
