# Generated by Django 5.1.2 on 2024-12-30 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_school_is_active'),
        ('core', '0015_remove_application_student_profile_application_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='application',
        ),
        migrations.RemoveIndex(
            model_name='application',
            name='core_applic_status_148db8_idx',
        ),
        migrations.RemoveIndex(
            model_name='application',
            name='core_applic_applica_89fdb8_idx',
        ),
        migrations.RemoveField(
            model_name='application',
            name='application_type',
        ),
        migrations.RemoveField(
            model_name='application',
            name='interview_date',
        ),
        migrations.RemoveField(
            model_name='application',
            name='previous_school_address',
        ),
        migrations.RemoveField(
            model_name='application',
            name='previous_school_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
        migrations.AddField(
            model_name='application',
            name='address',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='applicant_image',
            field=models.ImageField(blank=True, null=True, upload_to='applicant_images/'),
        ),
        migrations.AddField(
            model_name='application',
            name='application_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='parent_contact',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='previous_result',
            field=models.FileField(blank=True, null=True, upload_to='previous_results/'),
        ),
        migrations.AddField(
            model_name='application',
            name='previous_school',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_code',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='class_level',
            field=models.CharField(choices=[('Nursery 1', 'Nursery 1'), ('Nursery 2', 'Nursery 2'), ('Nursery 3', 'Nursery 3'), ('Class 1', 'Class 1'), ('Class 2', 'Class 2'), ('Class 3', 'Class 3'), ('Class 4', 'Class 4'), ('Class 5', 'Class 5'), ('Class 6', 'Class 6'), ('JSS 1', 'JSS 1'), ('JSS 2', 'JSS 2'), ('JSS 3', 'JSS 3'), ('SS 1', 'SS 1'), ('SS 2', 'SS 2'), ('SS 3', 'SS 3')], max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='account.school'),
        ),
        migrations.AlterField(
            model_name='application',
            name='school_level',
            field=models.CharField(choices=[('nursery', 'Nursery'), ('primary', 'Primary'), ('secondary', 'Secondary')], max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
