# Generated by Django 5.1.2 on 2024-12-30 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_tutorprofile_rating_tutorrequest_deadline_and_more'),
        ('core', '0016_remove_document_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='account.school'),
        ),
    ]
