# Generated by Django 5.1.2 on 2024-12-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_application_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='application_qr_codes/'),
        ),
    ]
