# Generated by Django 5.1.2 on 2025-01-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('chunk_text', models.TextField()),
                ('embedding', models.BinaryField()),
                ('metadata', models.JSONField()),
            ],
        ),
    ]
