# Generated by Django 5.1.2 on 2025-02-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_core', '0002_reportcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='report_cards/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
