# Generated by Django 5.1.2 on 2025-02-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_core', '0003_reportcardimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.CharField(choices=[('Nursery 1', 'Nursery 1'), ('Nursery 2', 'Nursery 2'), ('Nursery 3', 'Nursery 3'), ('Class 1', 'Class 1'), ('Class 2', 'Class 2'), ('Class 3', 'Class 3'), ('Class 4', 'Class 4'), ('Class 5', 'Class 5'), ('Class 6', 'Class 6'), ('JSS 1', 'JSS 1'), ('JSS 2', 'JSS 2'), ('JSS 3', 'JSS 3'), ('SS 1', 'SS 1'), ('SS 2', 'SS 2'), ('SS 3', 'SS 3')], max_length=10)),
                ('topic', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('Multiple Choice Questions', 'Multiple Choice Questions'), ('Essay', 'Essay'), ('Scenario Based', 'Scenario Based'), ('Class Exercise', 'Class Exercise'), ('Homework', 'Homework'), ('Interactive Session', 'Interactive Session'), ('Experiment', 'Experiment'), ('Practical', 'Practical')], max_length=30)),
                ('difficulty_level', models.CharField(choices=[('Simple', 'Simple'), ('Average', 'Average'), ('Hard', 'Hard'), ('Logical', 'Logical')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
