# Generated by Django 5.1.2 on 2025-02-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_core', '0004_resourcemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcemodel',
            name='number_of_questions',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
