# Generated by Django 5.1.2 on 2025-02-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_core', '0005_resourcemodel_number_of_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcemodel',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
