# Generated by Django 5.1.2 on 2025-02-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_core', '0006_resourcemodel_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcemodel',
            name='subject',
            field=models.CharField(choices=[('English', 'English'), ('Mathematics', 'Mathematics')], default='English', max_length=20),
        ),
    ]
