# Generated by Django 5.1.15 on 2026-02-16 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_core", "0007_resourcemodel_subject"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FlashcardSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=255)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Nursery 1", "Nursery 1"),
                            ("Nursery 2", "Nursery 2"),
                            ("Nursery 3", "Nursery 3"),
                            ("Class 1", "Class 1"),
                            ("Class 2", "Class 2"),
                            ("Class 3", "Class 3"),
                            ("Class 4", "Class 4"),
                            ("Class 5", "Class 5"),
                            ("Class 6", "Class 6"),
                            ("JSS 1", "JSS 1"),
                            ("JSS 2", "JSS 2"),
                            ("JSS 3", "JSS 3"),
                            ("SS 1", "SS 1"),
                            ("SS 2", "SS 2"),
                            ("SS 3", "SS 3"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cards", models.JSONField()),
                ("total_cards", models.PositiveIntegerField(default=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flashcard_sets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuizSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=100)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Nursery 1", "Nursery 1"),
                            ("Nursery 2", "Nursery 2"),
                            ("Nursery 3", "Nursery 3"),
                            ("Class 1", "Class 1"),
                            ("Class 2", "Class 2"),
                            ("Class 3", "Class 3"),
                            ("Class 4", "Class 4"),
                            ("Class 5", "Class 5"),
                            ("Class 6", "Class 6"),
                            ("JSS 1", "JSS 1"),
                            ("JSS 2", "JSS 2"),
                            ("JSS 3", "JSS 3"),
                            ("SS 1", "SS 1"),
                            ("SS 2", "SS 2"),
                            ("SS 3", "SS 3"),
                        ],
                        max_length=20,
                    ),
                ),
                ("score", models.PositiveIntegerField(default=0)),
                ("total_questions", models.PositiveIntegerField(default=5)),
                ("quiz_data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
