# Generated by Django 5.1.15 on 2026-02-18 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_core", "0008_flashcardset_quizsession"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("NPSE", "NPSE"),
                            ("BECE", "BECE"),
                            ("WASSCE", "WASSCE"),
                        ],
                        max_length=10,
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                (
                    "paper_type",
                    models.CharField(
                        choices=[
                            ("objectives", "Objectives (MCQ)"),
                            ("theory", "Theory"),
                        ],
                        max_length=15,
                    ),
                ),
                ("num_questions", models.PositiveIntegerField()),
                ("time_minutes", models.PositiveIntegerField()),
                ("instructions", models.TextField(blank=True)),
            ],
            options={
                "unique_together": {("exam_type", "subject", "paper_type")},
            },
        ),
        migrations.CreateModel(
            name="ExamSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("questions_data", models.JSONField()),
                ("answers_data", models.JSONField(default=list)),
                ("score", models.PositiveIntegerField(blank=True, null=True)),
                ("total_marks", models.PositiveIntegerField(blank=True, null=True)),
                ("percentage", models.FloatField(blank=True, null=True)),
                ("grade", models.CharField(blank=True, max_length=5, null=True)),
                ("feedback", models.TextField(blank=True, null=True)),
                ("topic_breakdown", models.JSONField(blank=True, null=True)),
                (
                    "exam_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="ai_core.examconfig",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
